let contacts = [{ "id": 1, "name": "Haydon", "email": "hchidley0@usa.gov", "gender": "Male" },
{ "id": 2, "name": "Kearney", "email": "kbucher1@foxnews.com", "gender": "Male" },
{ "id": 3, "name": "Griffy", "email": "gavey2@cam.ac.uk", "gender": "Male" },
{ "id": 4, "name": "Shanta", "email": "sraisbeck3@imageshack.us", "gender": "Female" },
{ "id": 5, "name": "Corrina", "email": "cgratland4@tinyurl.com", "gender": "Female" },
{ "id": 6, "name": "Koressa", "email": "krimour5@google.nl", "gender": "Female" },
{ "id": 7, "name": "Kalvin", "email": "kclell6@buzzfeed.com", "gender": "Male" },
{ "id": 8, "name": "Si", "email": "sslora7@tinyurl.com", "gender": "Polygender" },
{ "id": 9, "name": "Issie", "email": "idobel8@cnet.com", "gender": "Female" },
{ "id": 10, "name": "Muire", "email": "mlivsey9@usa.gov", "gender": "Genderqueer" },
{ "id": 11, "name": "Kelby", "email": "khairyesa@nyu.edu", "gender": "Male" },
{ "id": 12, "name": "Barbabas", "email": "bauthersb@uiuc.edu", "gender": "Male" },
{ "id": 13, "name": "Benji", "email": "bprozesckyc@linkedin.com", "gender": "Male" },
{ "id": 14, "name": "Cyril", "email": "cscheud@photobucket.com", "gender": "Male" },
{ "id": 15, "name": "Ancell", "email": "ablounte@mysql.com", "gender": "Male" },
{ "id": 16, "name": "Aliza", "email": "abillf@ftc.gov", "gender": "Female" },
{ "id": 17, "name": "Meara", "email": "mbenardetteg@ca.gov", "gender": "Female" },
{ "id": 18, "name": "Hurlee", "email": "harchbouldh@php.net", "gender": "Male" },
{ "id": 19, "name": "Marabel", "email": "mfattorinii@github.io", "gender": "Female" },
{ "id": 20, "name": "Melisenda", "email": "mmackonochiej@mapquest.com", "gender": "Female" },
{ "id": 21, "name": "Putnem", "email": "pjacksk@angelfire.com", "gender": "Male" },
{ "id": 22, "name": "Dwayne", "email": "dlivingstonl@harvard.edu", "gender": "Genderqueer" },
{ "id": 23, "name": "Bink", "email": "bbirtsm@ning.com", "gender": "Male" },
{ "id": 24, "name": "Codie", "email": "croccon@rakuten.co.jp", "gender": "Male" },
{ "id": 25, "name": "Ross", "email": "rmunfordo@army.mil", "gender": "Male" },
{ "id": 26, "name": "Rand", "email": "rwoolensp@unesco.org", "gender": "Male" },
{ "id": 27, "name": "Blake", "email": "bkuhnwaldq@pinterest.com", "gender": "Male" },
{ "id": 28, "name": "Benedetto", "email": "bschoutr@yolasite.com", "gender": "Male" },
{ "id": 29, "name": "Wenona", "email": "wcrometts@163.com", "gender": "Female" },
{ "id": 30, "name": "Jereme", "email": "jrodingert@dot.gov", "gender": "Male" },
{ "id": 31, "name": "Chrisy", "email": "cleveyu@icq.com", "gender": "Male" },
{ "id": 32, "name": "Diandra", "email": "dchisnellv@angelfire.com", "gender": "Female" },
{ "id": 33, "name": "Krissie", "email": "kbaudessonw@freewebs.com", "gender": "Genderqueer" },
{ "id": 34, "name": "Roseanne", "email": "rastx@marriott.com", "gender": "Female" },
{ "id": 35, "name": "Rahel", "email": "rpeabodyy@geocities.jp", "gender": "Female" },
{ "id": 36, "name": "Ado", "email": "akristufekz@freewebs.com", "gender": "Male" },
{ "id": 37, "name": "Matilde", "email": "mschruur10@imgur.com", "gender": "Female" },
{ "id": 38, "name": "Dare", "email": "dbotwood11@marriott.com", "gender": "Male" },
{ "id": 39, "name": "Blinny", "email": "bdreinan12@amazonaws.com", "gender": "Female" },
{ "id": 40, "name": "Wiatt", "email": "wlemmers13@e-recht24.de", "gender": "Male" },
{ "id": 41, "name": "Bridget", "email": "bmalamore14@bloglines.com", "gender": "Female" },
{ "id": 42, "name": "Marijo", "email": "mgreder15@theglobeandmail.com", "gender": "Bigender" },
{ "id": 43, "name": "Debra", "email": "dhovie16@baidu.com", "gender": "Female" },
{ "id": 44, "name": "Karin", "email": "kcottel17@csmonitor.com", "gender": "Female" },
{ "id": 45, "name": "Nikola", "email": "nionn18@buzzfeed.com", "gender": "Male" },
{ "id": 46, "name": "Isacco", "email": "imilillo19@free.fr", "gender": "Genderfluid" },
{ "id": 47, "name": "Ariel", "email": "aproven1a@reverbnation.com", "gender": "Female" },
{ "id": 48, "name": "Rustie", "email": "rorchard1b@rambler.ru", "gender": "Male" },
{ "id": 49, "name": "Lucille", "email": "lfrancescone1c@hatena.ne.jp", "gender": "Female" },
{ "id": 50, "name": "Curcio", "email": "cshimmans1d@123-reg.co.uk", "gender": "Male" }]

//print contact email id 
for (contact of contacts) {
    console.log(contact.id)
}